on:
  push:
    branches: [gh-pages]

jobs:
  create_issues:
    runs-on: ubuntu-latest
    name: create-issue-steps
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout private actions
        uses: actions/checkout@v2
        with:
          repository: tbrockman/github-social-action
          ref: master
          token: ${{ secrets.GITHUB_TOKEN }}
          path: .github/actions/github-social-action
      - name: Create issues
        uses: ./.github/actions/github-social-action
        id: yabadaba
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }} 