on:
  push:
    branches: [gh-pages]

jobs:
  create_issues:
    runs-on: ubuntu-latest
    name: create-issue-steps
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create issues
        uses: tbrockman/social-action@1.0.2
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}